namespace NodeJS {
  interface ProcessEnv {
    NEXT_PUBLIC_EMAILJS_SERVICE_ID: string;
    NEXT_PUBLIC_EMAILJS_TEMPLATE_ID: string;
    NEXT_PUBLIC_EMAILJS_USER_PUBLIC_KEY: string;
    NEXT_PUBLIC_PAYPAL_CLIENT_ID: string;
    NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: string;
  }
}
